/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ServiceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "service";
};

export type SolutionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "solution";
};

export type IndustryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "industry";
};

export type ClientLogoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "clientLogo";
};

export type SuccessStoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "successStory";
};

export type CaseStudyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "caseStudy";
};

export type FaqReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "faq";
};

export type GeneralPage = {
  _id: string;
  _type: "generalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  openGraphImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type VideoEmbed = {
  _id: string;
  _type: "videoEmbed";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  embedUrl?: string;
  seo?: Seo;
};

export type ContactSettings = {
  _id: string;
  _type: "contactSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  address?: string;
  email?: string;
  phones?: Array<string>;
  mapUrl?: string;
  seo?: Seo;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  seo?: Seo;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  columns?: Array<{
    title?: string;
    links?: Array<
      {
        _key: string;
      } & Link
    >;
    _key: string;
  }>;
  legalLinks?: Array<
    {
      _key: string;
    } & Link
  >;
  seo?: Seo;
};

export type Cta = {
  _id: string;
  _type: "cta";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  primaryCta?: Link;
  secondaryCta?: Link;
  seo?: Seo;
};

export type Link = {
  _type: "link";
  label?: string;
  href?: string;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  answer?: string;
  seo?: Seo;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  eventDate?: string;
  seo?: Seo;
};

export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  seo?: Seo;
};

export type SuccessStory = {
  _id: string;
  _type: "successStory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  seo?: Seo;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  quote?: string;
  personName?: string;
  personRole?: string;
  seo?: Seo;
};

export type ClientLogo = {
  _id: string;
  _type: "clientLogo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  seo?: Seo;
};

export type Industry = {
  _id: string;
  _type: "industry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  seo?: Seo;
};

export type ServiceCategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "serviceCategory";
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  parent?: ServiceCategoryReference;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  seo?: Seo;
};

export type ServiceCategory = {
  _id: string;
  _type: "serviceCategory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  seo?: Seo;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  seo?: Seo;
};

export type Solution = {
  _id: string;
  _type: "solution";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  seo?: Seo;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  items?: Array<{
    label?: string;
    href?: string;
    children?: Array<
      {
        _key: string;
      } & Link
    >;
    _key: string;
  }>;
  contactCta?: Link;
};

export type TestimonialReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "testimonial";
};

export type EventReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "event";
};

export type CtaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "cta";
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  heroSlides?: Array<
    {
      _key: string;
    } & HeroSlide
  >;
  sections?: ArrayOf<
    | SolutionReference
    | TestimonialReference
    | SuccessStoryReference
    | FaqReference
    | EventReference
    | CtaReference
  >;
  seo?: Seo;
  sectionContent?: Array<{
    key?: string;
    eyebrow?: string;
    heading?: string;
    description?: string;
    cta?: Link;
    _key: string;
  }>;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type HeroSlide = {
  _type: "heroSlide";
  headline?: string;
  supportingText?: string;
  mediaType?: "image" | "video";
  desktopMedia?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  mobileMedia?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  primaryCta?: Link;
  secondaryCta?: Link;
  overlayStrength?: number;
  order?: number;
  visible?: boolean;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | ServiceReference
  | SolutionReference
  | IndustryReference
  | ClientLogoReference
  | SuccessStoryReference
  | CaseStudyReference
  | FaqReference
  | GeneralPage
  | Seo
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | VideoEmbed
  | ContactSettings
  | SiteSettings
  | Footer
  | Cta
  | Link
  | Faq
  | Event
  | CaseStudy
  | SuccessStory
  | Testimonial
  | ClientLogo
  | Industry
  | ServiceCategoryReference
  | Service
  | ServiceCategory
  | Product
  | Solution
  | Navigation
  | TestimonialReference
  | EventReference
  | CtaReference
  | Homepage
  | SanityFileAssetReference
  | HeroSlide
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/typegen-queries.ts
// Variable: TYPEGEN_HOMEPAGE
// Query: *[_type=="homepage"][0]{_id,_updatedAt,title}
export type TYPEGEN_HOMEPAGE_RESULT = {
  _id: string;
  _updatedAt: string;
  title: string | null;
} | null;

// Source: sanity/lib/typegen-queries.ts
// Variable: TYPEGEN_CLIENTS
// Query: *[_type=="clientLogo"&&active!=false]{_id,_updatedAt,title,"slug":slug.current,"imageUrl":image.asset->url}
export type TYPEGEN_CLIENTS_RESULT = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  imageUrl: string | null;
}>;

// Source: sanity/lib/typegen-queries.ts
// Variable: TYPEGEN_SOLUTIONS
// Query: *[_type=="solution"&&active!=false]{_id,_updatedAt,title,"slug":slug.current}
export type TYPEGEN_SOLUTIONS_RESULT = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
}>;

// Source: sanity/lib/typegen-queries.ts
// Variable: TYPEGEN_PRODUCTS
// Query: *[_type=="product"&&active!=false]{_id,_updatedAt,title,"slug":slug.current}
export type TYPEGEN_PRODUCTS_RESULT = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
}>;

// Source: sanity/lib/typegen-queries.ts
// Variable: TYPEGEN_SERVICE_CATEGORIES
// Query: *[_type=="serviceCategory"&&active!=false]{_id,_updatedAt,title,"slug":slug.current}
export type TYPEGEN_SERVICE_CATEGORIES_RESULT = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
}>;

// Source: sanity/lib/typegen-queries.ts
// Variable: TYPEGEN_SERVICES
// Query: *[_type=="service"&&active!=false]{_id,_updatedAt,title,"slug":slug.current}
export type TYPEGEN_SERVICES_RESULT = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
}>;

// Source: sanity/lib/typegen-queries.ts
// Variable: TYPEGEN_INDUSTRIES
// Query: *[_type=="industry"&&active!=false]{_id,_updatedAt,title,"slug":slug.current}
export type TYPEGEN_INDUSTRIES_RESULT = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
}>;

// Source: sanity/lib/typegen-queries.ts
// Variable: TYPEGEN_STORIES
// Query: *[_type=="successStory"&&active!=false]{_id,_updatedAt,title,"slug":slug.current}
export type TYPEGEN_STORIES_RESULT = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
}>;

// Source: sanity/lib/typegen-queries.ts
// Variable: TYPEGEN_CASE_STUDIES
// Query: *[_type=="caseStudy"&&active!=false]{_id,_updatedAt,title,"slug":slug.current}
export type TYPEGEN_CASE_STUDIES_RESULT = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
}>;

// Source: sanity/lib/typegen-queries.ts
// Variable: TYPEGEN_TESTIMONIALS
// Query: *[_type=="testimonial"&&active!=false]{_id,_updatedAt,title,quote}
export type TYPEGEN_TESTIMONIALS_RESULT = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  quote: string | null;
}>;

// Source: sanity/lib/typegen-queries.ts
// Variable: TYPEGEN_EVENTS
// Query: *[_type=="event"&&active!=false]{_id,_updatedAt,title,eventDate}
export type TYPEGEN_EVENTS_RESULT = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  eventDate: string | null;
}>;

// Source: sanity/lib/typegen-queries.ts
// Variable: TYPEGEN_FAQS
// Query: *[_type=="faq"&&active!=false]{_id,_updatedAt,title,answer}
export type TYPEGEN_FAQS_RESULT = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  answer: string | null;
}>;

// Source: sanity/lib/typegen-queries.ts
// Variable: TYPEGEN_CTAS
// Query: *[_type=="cta"&&active!=false]{_id,_updatedAt,title,primaryCta}
export type TYPEGEN_CTAS_RESULT = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  primaryCta: Link | null;
}>;

// Source: sanity/lib/typegen-queries.ts
// Variable: TYPEGEN_VIDEOS
// Query: *[_type=="videoEmbed"&&active!=false]{_id,_updatedAt,title,embedUrl}
export type TYPEGEN_VIDEOS_RESULT = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  embedUrl: string | null;
}>;

// Source: sanity/lib/typegen-queries.ts
// Variable: TYPEGEN_NAVIGATION
// Query: *[_type=="navigation"][0]{_id,_updatedAt,title}
export type TYPEGEN_NAVIGATION_RESULT = {
  _id: string;
  _updatedAt: string;
  title: string | null;
} | null;

// Source: sanity/lib/typegen-queries.ts
// Variable: TYPEGEN_FOOTER
// Query: *[_type=="footer"][0]{_id,_updatedAt,title}
export type TYPEGEN_FOOTER_RESULT = {
  _id: string;
  _updatedAt: string;
  title: string | null;
} | null;

// Source: sanity/lib/typegen-queries.ts
// Variable: TYPEGEN_SITE
// Query: *[_type=="siteSettings"][0]{_id,_updatedAt,title}
export type TYPEGEN_SITE_RESULT = {
  _id: string;
  _updatedAt: string;
  title: string | null;
} | null;

// Source: sanity/lib/typegen-queries.ts
// Variable: TYPEGEN_CONTACT
// Query: *[_type=="contactSettings"][0]{_id,_updatedAt,title,email}
export type TYPEGEN_CONTACT_RESULT = {
  _id: string;
  _updatedAt: string;
  title: string | null;
  email: string | null;
} | null;

// Source: sanity/lib/typegen-queries.ts
// Variable: TYPEGEN_PAGE
// Query: *[_type=="generalPage"&&slug.current==$slug&&active!=false][0]{_id,_updatedAt,title,"slug":slug.current}
export type TYPEGEN_PAGE_RESULT = {
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
} | null;

// Source: sanity/lib/typegen-queries.ts
// Variable: TYPEGEN_SITEMAP
// Query: *[_type in ["service","solution","product","industry","successStory","caseStudy","event","generalPage"]&&active!=false]{_id,_type,"slug":slug.current,_updatedAt}
export type TYPEGEN_SITEMAP_RESULT = Array<
  | {
      _id: string;
      _type: "caseStudy";
      slug: string | null;
      _updatedAt: string;
    }
  | {
      _id: string;
      _type: "event";
      slug: string | null;
      _updatedAt: string;
    }
  | {
      _id: string;
      _type: "generalPage";
      slug: string | null;
      _updatedAt: string;
    }
  | {
      _id: string;
      _type: "industry";
      slug: string | null;
      _updatedAt: string;
    }
  | {
      _id: string;
      _type: "product";
      slug: string | null;
      _updatedAt: string;
    }
  | {
      _id: string;
      _type: "service";
      slug: string | null;
      _updatedAt: string;
    }
  | {
      _id: string;
      _type: "solution";
      slug: string | null;
      _updatedAt: string;
    }
  | {
      _id: string;
      _type: "successStory";
      slug: string | null;
      _updatedAt: string;
    }
>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type=="homepage"][0]{_id,_updatedAt,title}': TYPEGEN_HOMEPAGE_RESULT;
    '*[_type=="clientLogo"&&active!=false]{_id,_updatedAt,title,"slug":slug.current,"imageUrl":image.asset->url}': TYPEGEN_CLIENTS_RESULT;
    '*[_type=="solution"&&active!=false]{_id,_updatedAt,title,"slug":slug.current}': TYPEGEN_SOLUTIONS_RESULT;
    '*[_type=="product"&&active!=false]{_id,_updatedAt,title,"slug":slug.current}': TYPEGEN_PRODUCTS_RESULT;
    '*[_type=="serviceCategory"&&active!=false]{_id,_updatedAt,title,"slug":slug.current}': TYPEGEN_SERVICE_CATEGORIES_RESULT;
    '*[_type=="service"&&active!=false]{_id,_updatedAt,title,"slug":slug.current}': TYPEGEN_SERVICES_RESULT;
    '*[_type=="industry"&&active!=false]{_id,_updatedAt,title,"slug":slug.current}': TYPEGEN_INDUSTRIES_RESULT;
    '*[_type=="successStory"&&active!=false]{_id,_updatedAt,title,"slug":slug.current}': TYPEGEN_STORIES_RESULT;
    '*[_type=="caseStudy"&&active!=false]{_id,_updatedAt,title,"slug":slug.current}': TYPEGEN_CASE_STUDIES_RESULT;
    '*[_type=="testimonial"&&active!=false]{_id,_updatedAt,title,quote}': TYPEGEN_TESTIMONIALS_RESULT;
    '*[_type=="event"&&active!=false]{_id,_updatedAt,title,eventDate}': TYPEGEN_EVENTS_RESULT;
    '*[_type=="faq"&&active!=false]{_id,_updatedAt,title,answer}': TYPEGEN_FAQS_RESULT;
    '*[_type=="cta"&&active!=false]{_id,_updatedAt,title,primaryCta}': TYPEGEN_CTAS_RESULT;
    '*[_type=="videoEmbed"&&active!=false]{_id,_updatedAt,title,embedUrl}': TYPEGEN_VIDEOS_RESULT;
    '*[_type=="navigation"][0]{_id,_updatedAt,title}': TYPEGEN_NAVIGATION_RESULT;
    '*[_type=="footer"][0]{_id,_updatedAt,title}': TYPEGEN_FOOTER_RESULT;
    '*[_type=="siteSettings"][0]{_id,_updatedAt,title}': TYPEGEN_SITE_RESULT;
    '*[_type=="contactSettings"][0]{_id,_updatedAt,title,email}': TYPEGEN_CONTACT_RESULT;
    '*[_type=="generalPage"&&slug.current==$slug&&active!=false][0]{_id,_updatedAt,title,"slug":slug.current}': TYPEGEN_PAGE_RESULT;
    '*[_type in ["service","solution","product","industry","successStory","caseStudy","event","generalPage"]&&active!=false]{_id,_type,"slug":slug.current,_updatedAt}': TYPEGEN_SITEMAP_RESULT;
  }
}
