/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

type ArrayOf<T> = Array<
  T & {
    _key: string;
  }
>;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ServiceReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "service";
};

export type SolutionReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "solution";
};

export type IndustryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "industry";
};

export type ClientLogoReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "clientLogo";
};

export type SuccessStoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "successStory";
};

export type CaseStudyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "caseStudy";
};

export type FaqReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "faq";
};

export type GeneralPage = {
  _id: string;
  _type: "generalPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  status?: "draft" | "published";
  seo?: Seo;
};

export type Seo = {
  _type: "seo";
  metaTitle?: string;
  metaDescription?: string;
  openGraphImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type VideoEmbed = {
  _id: string;
  _type: "videoEmbed";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  status?: "draft" | "published";
  seo?: Seo;
};

export type ContactSettings = {
  _id: string;
  _type: "contactSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  status?: "draft" | "published";
  seo?: Seo;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  status?: "draft" | "published";
  seo?: Seo;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  status?: "draft" | "published";
  seo?: Seo;
};

export type Cta = {
  _id: string;
  _type: "cta";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  status?: "draft" | "published";
  seo?: Seo;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  status?: "draft" | "published";
  seo?: Seo;
};

export type Event = {
  _id: string;
  _type: "event";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  status?: "draft" | "published";
  seo?: Seo;
};

export type CaseStudy = {
  _id: string;
  _type: "caseStudy";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  status?: "draft" | "published";
  seo?: Seo;
};

export type SuccessStory = {
  _id: string;
  _type: "successStory";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  status?: "draft" | "published";
  seo?: Seo;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  status?: "draft" | "published";
  seo?: Seo;
};

export type ClientLogo = {
  _id: string;
  _type: "clientLogo";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  status?: "draft" | "published";
  seo?: Seo;
};

export type Industry = {
  _id: string;
  _type: "industry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  status?: "draft" | "published";
  seo?: Seo;
};

export type Service = {
  _id: string;
  _type: "service";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  status?: "draft" | "published";
  seo?: Seo;
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  status?: "draft" | "published";
  seo?: Seo;
};

export type Solution = {
  _id: string;
  _type: "solution";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  summary?: string;
  eyebrow?: string;
  active?: boolean;
  featured?: boolean;
  accessibleLabel?: string;
  websiteUrl?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?:
          "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  features?: Array<string>;
  benefits?: Array<string>;
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  relatedServices?: Array<
    {
      _key: string;
    } & ServiceReference
  >;
  relatedSolutions?: Array<
    {
      _key: string;
    } & SolutionReference
  >;
  relatedIndustries?: Array<
    {
      _key: string;
    } & IndustryReference
  >;
  relatedClients?: Array<
    {
      _key: string;
    } & ClientLogoReference
  >;
  relatedStories?: ArrayOf<SuccessStoryReference | CaseStudyReference>;
  youtubeUrls?: Array<string>;
  faqs?: Array<
    {
      _key: string;
    } & FaqReference
  >;
  socialLinks?: Array<{
    label?: string;
    url?: string;
    _key: string;
  }>;
  status?: "draft" | "published";
  seo?: Seo;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  items?: Array<{
    label?: string;
    href?: string;
    children?: Array<
      {
        _key: string;
      } & Link
    >;
    _key: string;
  }>;
  contactCta?: Link;
  status?: "draft" | "published";
};

export type Link = {
  _type: "link";
  label?: string;
  href?: string;
};

export type TestimonialReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "testimonial";
};

export type EventReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "event";
};

export type CtaReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "cta";
};

export type Homepage = {
  _id: string;
  _type: "homepage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  heroSlides?: Array<
    {
      _key: string;
    } & HeroSlide
  >;
  sections?: ArrayOf<
    | SolutionReference
    | TestimonialReference
    | SuccessStoryReference
    | FaqReference
    | EventReference
    | CtaReference
  >;
  seo?: Seo;
  status?: "draft" | "published";
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type HeroSlide = {
  _type: "heroSlide";
  headline?: string;
  supportingText?: string;
  mediaType?: "image" | "video";
  desktopMedia?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  mobileMedia?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  poster?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  primaryCta?: Link;
  secondaryCta?: Link;
  overlayStrength?: number;
  order?: number;
  visible?: boolean;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | ServiceReference
  | SolutionReference
  | IndustryReference
  | ClientLogoReference
  | SuccessStoryReference
  | CaseStudyReference
  | FaqReference
  | GeneralPage
  | Seo
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | VideoEmbed
  | ContactSettings
  | SiteSettings
  | Footer
  | Cta
  | Faq
  | Event
  | CaseStudy
  | SuccessStory
  | Testimonial
  | ClientLogo
  | Industry
  | Service
  | Product
  | Solution
  | Navigation
  | Link
  | TestimonialReference
  | EventReference
  | CtaReference
  | Homepage
  | SanityFileAssetReference
  | HeroSlide
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
